//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace GarantiasDell.com.dell.xserv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AssetServiceSoap", Namespace="http://support.dell.com/WebServices/")]
    public partial class AssetService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAssetInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AssetService() {
            this.Url = global::GarantiasDell.Properties.Settings.Default.GarantiasDell_com_dell_xserv_AssetService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAssetInformationCompletedEventHandler GetAssetInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://support.dell.com/WebServices/GetAssetInformation", RequestNamespace="http://support.dell.com/WebServices/", ResponseNamespace="http://support.dell.com/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Asset[] GetAssetInformation(System.Guid guid, string applicationName, string serviceTags) {
            object[] results = this.Invoke("GetAssetInformation", new object[] {
                        guid,
                        applicationName,
                        serviceTags});
            return ((Asset[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAssetInformationAsync(System.Guid guid, string applicationName, string serviceTags) {
            this.GetAssetInformationAsync(guid, applicationName, serviceTags, null);
        }
        
        /// <remarks/>
        public void GetAssetInformationAsync(System.Guid guid, string applicationName, string serviceTags, object userState) {
            if ((this.GetAssetInformationOperationCompleted == null)) {
                this.GetAssetInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssetInformationOperationCompleted);
            }
            this.InvokeAsync("GetAssetInformation", new object[] {
                        guid,
                        applicationName,
                        serviceTags}, this.GetAssetInformationOperationCompleted, userState);
        }
        
        private void OnGetAssetInformationOperationCompleted(object arg) {
            if ((this.GetAssetInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssetInformationCompleted(this, new GetAssetInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://support.dell.com/WebServices/")]
    public partial class Asset {
        
        private AssetHeaderData assetHeaderDataField;
        
        private EntitlementData[] entitlementsField;
        
        private Asset[] dupilcateAssetsField;
        
        private string userMessageField;
        
        /// <comentarios/>
        public AssetHeaderData AssetHeaderData {
            get {
                return this.assetHeaderDataField;
            }
            set {
                this.assetHeaderDataField = value;
            }
        }
        
        /// <comentarios/>
        public EntitlementData[] Entitlements {
            get {
                return this.entitlementsField;
            }
            set {
                this.entitlementsField = value;
            }
        }
        
        /// <comentarios/>
        public Asset[] DupilcateAssets {
            get {
                return this.dupilcateAssetsField;
            }
            set {
                this.dupilcateAssetsField = value;
            }
        }
        
        /// <comentarios/>
        public string UserMessage {
            get {
                return this.userMessageField;
            }
            set {
                this.userMessageField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://support.dell.com/WebServices/")]
    public partial class AssetHeaderData {
        
        private string serviceTagField;
        
        private string systemIDField;
        
        private string buidField;
        
        private string regionField;
        
        private string systemTypeField;
        
        private string systemModelField;
        
        private System.DateTime systemShipDateField;
        
        /// <comentarios/>
        public string ServiceTag {
            get {
                return this.serviceTagField;
            }
            set {
                this.serviceTagField = value;
            }
        }
        
        /// <comentarios/>
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <comentarios/>
        public string Buid {
            get {
                return this.buidField;
            }
            set {
                this.buidField = value;
            }
        }
        
        /// <comentarios/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <comentarios/>
        public string SystemType {
            get {
                return this.systemTypeField;
            }
            set {
                this.systemTypeField = value;
            }
        }
        
        /// <comentarios/>
        public string SystemModel {
            get {
                return this.systemModelField;
            }
            set {
                this.systemModelField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime SystemShipDate {
            get {
                return this.systemShipDateField;
            }
            set {
                this.systemShipDateField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://support.dell.com/WebServices/")]
    public partial class EntitlementData {
        
        private string serviceLevelCodeField;
        
        private string serviceLevelDescriptionField;
        
        private string providerField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private int daysLeftField;
        
        private EntitlementType entitlementTypeField;
        
        /// <comentarios/>
        public string ServiceLevelCode {
            get {
                return this.serviceLevelCodeField;
            }
            set {
                this.serviceLevelCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string ServiceLevelDescription {
            get {
                return this.serviceLevelDescriptionField;
            }
            set {
                this.serviceLevelDescriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <comentarios/>
        public int DaysLeft {
            get {
                return this.daysLeftField;
            }
            set {
                this.daysLeftField = value;
            }
        }
        
        /// <comentarios/>
        public EntitlementType EntitlementType {
            get {
                return this.entitlementTypeField;
            }
            set {
                this.entitlementTypeField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://support.dell.com/WebServices/")]
    public enum EntitlementType {
        
        /// <comentarios/>
        Expired,
        
        /// <comentarios/>
        Active,
        
        /// <comentarios/>
        Future,
        
        /// <comentarios/>
        Credited,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetAssetInformationCompletedEventHandler(object sender, GetAssetInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssetInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssetInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Asset[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Asset[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591